### ISSUE TITLE
Support multiple parents (parent Ids) 

### ISSUE THREAD

**Issue by panosdemetriou** [remcoplasmeyer/flowy-vue#15]
@remcoplasmeyer Very useful plugin! Just a question, is there any extension for supporting multiple parent Ids or is it planned for a future release? If not, do you have any suggestions/ tips on how to implement this modification?

**Comment by hottehead** [comment]
Any reason why this was closed? 
I was about to ask for the same. Multiple parents would be a great extension. I tried setting an array of parent ids but that does not work.

**Comment by nabenzine** [comment]
It would be a game changer feature if it could be implemented !!

**Comment by KjetilHaaheim** [comment]
It is no use, I have spent much time to improve the library, with active and merged PRs, as well as sponsoring the project. Creator has clearly abandoned the project.
