### ISSUE TITLE
Flow through answers to questions.

### ISSUE THREAD

**Issue by tiagosmartinho** [remcoplasmeyer/flowy-vue#26]
Hi @remcoplasmeyer,

First of all, congratulations on the project, it is brutal 💯  🔥 

Now the reason why I write, at the moment I am inserted in a project in which I have to do flow of this kind, however there are some variants that I still haven't been able to understand if it is possible or not to do it with Flowy.

Basically, the objective is to create a script, with multi-selection questions, in which each possible answer takes a path.

Dummy example:
```
What brought you to our website today?
1. I'm looking to buy
2. I'm just browsing
...
```

And the objective is that each answer has a certain flow.

I have here a print of an example that is intended.

![Screenshot 2021-05-14 at 14 57 17](https://user-images.githubusercontent.com/22690341/118281090-c1074180-b4c4-11eb-9780-c0cf99fb09b7.png)

Do you think it is possible to achieve this with Flowy or if not, its implementation will be very difficult?

**Comment by remcoplasmeyer** [comment]
Hi @tiagosmartinho, thank you very much! 

Your use case should be doable with flowy-vue :)
