### ISSUE TITLE
Zoom in / out and panning

### ISSUE THREAD

**Issue by blurdylan** [remcoplasmeyer/flowy-vue#27]
Great library right here, i already intergrated it in my app.

I need a zoom/pan feature (maybe already implemented ?). I would like to have the author's take on how could I go about making it.

maybe trying to add a panzoom library like this one: https://github.com/anvaka/panzoom.
or submit a PR for this using js scale and transformation.

**Comment by remcoplasmeyer** [comment]
hi @blurdylan, I'd love that but I'm afraid flowy-vue is a combination of html and elements (nodes) and svg (lines inbetween) - I'm not sure how to solve :)
