### ISSUE TITLE
Is the underlying tree data structure exposed?

### ISSUE THREAD

**Issue by rfynes** [remcoplasmeyer/flowy-vue#28]
I have a need to identify whether or not the target node of a dragged node is currently a child of the dragged node (either directly or somewhere further down the line). Presumably there is already some data structure under the hood representing the tree, so it would be great if I could do a lookup to get straight to the target node and easily identify all the children. Is that data structure exposed at all or is there any function I can call that would help? Love the plugin, thanks a lot!

**Comment by remcoplasmeyer** [comment]
All of this data should be exposed in the `nodes` you supply yourself. Every node has a `parentId` referring to the parent node. Flowy Vue itself doesn't offer any utilities for this.
