### ISSUE TITLE
Vuetify support?

### ISSUE THREAD

**Issue by redijedi** [remcoplasmeyer/flowy-vue#29]
I've tried to get vuetify to work in the same way that quasar seems to, but continually get `Unknown custom element` errors and no rendering. Is there any recommended approach for using other UI frameworks?

**Comment by remcoplasmeyer** [comment]
Hi @redijedi, I'll gladly look into it if you can provide a reproducing repo. At the moment I'm guessing however this error is not due to flowy vue.

**Comment by KjetilHaaheim** [comment]
> I've tried to get vuetify to work in the same way that quasar seems to, but continually get `Unknown custom element` errors and no rendering. Is there any recommended approach for using other UI frameworks?

I have no problems using flowy with Vuetify. Example of FlowBlock:
```js 
<template>
	<div class="ma-0 pa-0">
		<flowy-drag-handle>
			<v-card
				outlined
				:color="node.color"
				cols="auto"
				width="140"
				height="80"
				class="d-flex flex-column align-center text-center pt-2"
			>
				<h3 class="caption" v-text="node.title" />
				<v-card-actions>
					<v-btn block style="width: 100%" color="grey-7" text>
						<v-icon large>mdi-drag-horizontal</v-icon>
					</v-btn>
				</v-card-actions>
			</v-card>
		</flowy-drag-handle>
	</div>
</template>

<script>
export default {
	name: 'FlowBlock',

	props: {
		node: Object,
	},
}
</script>
```

My block is globally imported:
```js 
import FlowBlock from '@/components/flow/FlowBlock'
Vue.component('FlowBlock', FlowBlock)
```

In your dataset, make sure each item contains the `nodeComponent` property:
```js
const nodes = [
  {
    id: "node-420,
    name: "Noodle",
    parentId: -1,
    nodeComponent: "FlowBlock"
  }
]
```

**Comment by redijedi** [comment]
Thanks for the quick reply! I found that the inline template approach didn't work, but the separate component approach as you described worked well. Thanks!
