### ISSUE TITLE
Unknown custom element: <q-card>

### ISSUE THREAD

**Issue by muhammad-Ali-Nawaz** [remcoplasmeyer/flowy-vue#31]
app.js:65959 [Vue warn]: Unknown custom element: <q-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <DemoBlock>
       <Draggable> at src/components/Draggable.vue
         <FlowyNewBlock>
           <CreateStoryV> at resources/assets/js/components/CreateStoryV.vue
             <Root>

**Comment by remcoplasmeyer** [comment]
@muhammad-Ali-Nawaz please provide a reproducing repo, this issue is not related to flowy vue as far as I'm concerned. q-card is a quasar component
