### ISSUE TITLE
DragStop never triggered

### ISSUE THREAD

**Issue by jappyjan** [remcoplasmeyer/flowy-vue#38]
It seems like the "@drag-stop" event from <FlowyNewBlock /> is never triggered and instead a @drag-start (or better said multiple) are triggered when dropping a new block onto <Flowy />

I wanted to add a @drag-stop handler to be able to add first-level parent nodes whenever a node is dropped on the <Flowy /> component instead of at the end of an existing node but the event is never triggered...

**Comment by KjetilHaaheim** [comment]
Hi @jappyjan! If I am understanding your issue correctly, you are not getting a drop event when dropping a new block onto the center of block, and not at the end.

If this is the case, there is an answer! The flow boxes have a dropzone, which is limited to the lower part of the component. I have outlined this area here:
![Screenshot 2021-08-05 at 00 47 56](https://user-images.githubusercontent.com/2472468/128265236-c38e3474-f6ce-4f4a-8d14-38f2d0efcc02.png)

The way I have used top level, is to use a special custom block as the start of the tree. Every block dropped under this, will be "first level". I hope this was relevant, please let me know if I misinterpreted.
