### ISSUE TITLE
Property appendTo : 'body' might not be working

### ISSUE THREAD

**Issue by neelrocketbots** [remcoplasmeyer/flowy-vue#42]
Hey, I believe the property `appendTo : 'body'` is not being passed properly to draggable. This causes a weird positioning issue for the draggable-mirror if the container is being scaled. The draggable-mirror is still attached to the container rather than the body

**Comment by maxganiev** [comment]
> Hey, I believe the property `appendTo : 'body'` is not being passed properly to draggable. This causes a weird positioning issue for the draggable-mirror if the container is being scaled. The draggable-mirror is still attached to the container rather than the body

@neelrocketbots hi, did you manage to solve this issue?
