### ISSUE TITLE
SVG horizontal connectors breaking on zooming out

### ISSUE THREAD

**Issue by shefaligupta** [remcoplasmeyer/flowy-vue#67]
Hi Remco, Kudos for writing this one. :)

I have been using this for my current work. I have also added a minimap with this and some zoom features. But as soon as I zoom out to less than 1, the horizontal lines start breaking. 

<img width="376" alt="Screenshot 2023-04-18 at 11 34 07 AM" src="https://user-images.githubusercontent.com/7941880/232736008-04f49d09-28ac-4ca8-ae56-5fc40ff625e4.png">

Do you know a way to fix this?

**Comment by maxganiev** [comment]
@shefaligupta hi, did you find the solution? I got the same problem with transform:scale. this seems to be a workaround, but browser support for css zoom is not really good in terms of cross-browserness.

Lines zoom and scale recalculating each time zoomer value changes (transform: scale value changes)

![image](https://user-images.githubusercontent.com/63904631/235855723-4fd6a05e-916f-407f-bcfc-6825550c0ea1.png)

**Comment by shefaligupta** [comment]
@maxganiev - fixed it by only using zoom on the parent container instead of transform.
```this.$refs.flowWrapper.style.zoom = 1;```
<img width="921" alt="Screenshot 2023-10-14 at 4 10 52 PM" src="https://github.com/remcoplasmeyer/flowy-vue/assets/7941880/0742accd-4592-46f3-8e50-96d9fcc21287">

**Comment by maxganiev** [comment]
@shefaligupta zoom has poor cross-browser compatibility, and is non-standard feature that is not recommended to use in production https://developer.mozilla.org/en-US/docs/Web/CSS/zoom 
if you don't mind that - zoom can be an option, though it has bugs when drawing large schemas.

fyi, if you need cross-browser solution tested on large schemas - more than welcome to my repo (this is now moved to production and connected to real backend service) 
https://github.com/maxganiev/flowy-draggable-vue
demo: https://schema-draggable.netlify.app/
